export const KEYS = {
  DATA: 'data',
  TOKEN: 'token',
  STATUS: 'status',
  EVENT: 'event',
  KICK_OFF_TIME: 'kickoff_time',
  TEAMS: 'teams',
  TEAM: 'team',
  ID: 'id',
  SHORT_NAME: 'short_name',
  ELEMENTS: 'elements',
  ELEMENT_TYPE: 'element_type',
  WEB_NAME: 'web_name',
  EXPLAIN: 'explain',
}
