export const ERROR_MSGS = {
  IMPROPER_REQUEST_PAYLOAD: 'Request Params or Request Body not found',
  USER_EXISTS: 'User with given email already exists',
  FPL_USER_NOT_FOUND: 'FPL Details for userID not found',
  PL_TEAM_DATA_NOT_ERROR: 'PL team data not found',
  PL_PLAYERS_DATA_NOT_ERROR: 'PL players data not found',
  PL_PLAYERS_LIVE_DATA_NOT_ERROR: 'PL players live data not found',
  IMPROPER_USER_ID: 'Use ID Invalid ',
  LEAGUES_NOT_FOUND: 'No Leagues found',
  CREDENTIALS_NOT_MATCHING: 'Credential do not match',
  USER_DOESNT_EXIST: 'User with this email doesnt exist',
  PASSWORDS_DONT_MATCH: 'Passwords do not match',
  TOKEN_NOT_FOUND: 'Token Not Found',
  INVALID_TOKEN: 'Invalid Token ',
  REFRESH_TOKEN_DONT_MATCH: 'Refresh Tokens do not match',
  GET_EVENT_STATUS_FAILED: 'Getting Event details failed',
  GET_EVENT_FIXTURES_FAILED: 'Getting Event Fixture details failed',
  GET_BOOTSTRAP_DATA_FOR_TEAMS_FAILED:
    'Getting teams from Bootstrap data failed',
  GET_BOOTSTRAP_DATA_FAILED: 'Getting Bootstrap data failed',
  GET_FPL_LEAGUE_DATA_FAILED: 'Getting FPL League data failed',
  GET_USER_PICKS_FOR_GAMEWEEK_DATA_FAILED:
    'Getting user picks for gameweek data failed',
  INVALID_GAMEWEEKID_SENT: 'Invalid Gameweek ID sent',
  INVALID_USER_ID: 'Invalid user ID sent',
}
export const INFO_MSGS = {
  IS_USER_FOUND_STATUS: 'User Detail found status',
  DOES_CREDS_MATCH: 'User Credentials match status',
  FPL_USER_DETAILS: 'FPL User details status',
  LAST_WATCHED_LEAGUE_STATUS: 'Last watched league ID',
  CREATED_USER_DETAILS: 'Created user details ',
  TOKEN_CREATED: 'Token created ',
  REFRESH_TOKEN_MATCH_STATUS: 'User Refresh Token match status',
  GET_EVENT_STATUS: 'Get Event Status data ',
  GET_BOOTSTRAP_DATA: 'Get Bootstrap data ',
  GET_USER_PICKS_DATA: 'Get user picks data ',
}
